import type { Metadata } from "next";
import { Beth_Ellen, Bigshot_One, Unna } from "next/font/google";
import "./globals.css";

const bethEllen = Beth_Ellen({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-beth-ellen",
});

const bigshotOne = Bigshot_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bigshot-one",
});

const unna = Unna({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-unna",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${bethEllen.variable} ${bigshotOne.variable} ${unna.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

